export default {
    FETCH: "GUESTBOOK_FETCH",
    FETCH_RECEIVED: "GUESTBOOK_FETCH_RECEIVED",
    FETCH_FAILED: "GUESTBOOK_FETCH_FAILED",
    ENTRY_UPDATED: "GUESTBOOK_ENTRY_UPDATED",
    DELETE: "GUESTBOOK_ENTRY_DELETE",
    DELETED: "GUESTBOOK_ENTRY_DELETED",
    NOT_DELETED: "GUESTBOOK_ENTRY_NOT_DELETED"
}